name: student_planner
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  intl: ^0.20.2
  googleapis: ^14.0.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.13
  url_launcher: ^6.3.1
  google_sign_in: ^6.2.1
  firebase_auth: ^5.5.2
  flutter_facebook_auth: ^7.1.1
  equatable: ^2.0.7
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  flex_color_scheme: ^8.2.0
  google_fonts: ^6.2.1
  file_picker: ^10.1.9
  image_picker: ^1.1.2
  firebase_storage: ^12.4.6
  flutter_local_notifications: ^19.2.1
  rxdart: ^0.28.0
  timezone: ^0.10.1
  table_calendar: ^3.2.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf

    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf

    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf

  assets:
    - assets/google.png
    - assets/facebook.png
