// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyqnmLg80E0ro2med-Rawg4Uj3uTUxbRA',
    appId: '1:635784511101:android:9cc9c7a8fde0da167dfb14',
    messagingSenderId: '635784511101',
    projectId: 'student-planner-app-d0eca',
    storageBucket: 'student-planner-app-d0eca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFcYfcXhN9uFfg-NThq3Ns5Ocr-1h49Ts',
    appId: '1:635784511101:ios:c0307495408977b57dfb14',
    messagingSenderId: '635784511101',
    projectId: 'student-planner-app-d0eca',
    storageBucket: 'student-planner-app-d0eca.firebasestorage.app',
    androidClientId: '635784511101-043mufmpf7al33o335vho8sdb7t90c8o.apps.googleusercontent.com',
    iosClientId: '635784511101-qq1len8k6epr5iohrf00af4olm2n87em.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentPlanner',
  );
}
